
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzgxmmgghoiiyddebwrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Z3htbWdnaG9paXlkZGVid3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDE3MzMsImV4cCI6MjA2OTc3NzczM30.gzI5CAdCdCbcc-jbRcJe2hjXWnQX7Yc8KqWWKFypZdU";

// Ensure we have valid URLs before creating the client
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase configuration missing');
  throw new Error('Supabase URL and key are required');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
